/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Deepcrawl } from "./deepcrawl.js";

export class DeepcrawlApp extends ClientSDK {
  private _deepcrawl?: Deepcrawl;
  get deepcrawl(): Deepcrawl {
    return (this._deepcrawl ??= new Deepcrawl(this._options));
  }
}
