import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  type EnvTarget,
  type EnvVarGroup,
  getEnvVarsForTarget,
} from '@deepcrawl/runtime/env';
import { formatDotenvValue, parseDotenv, writeFileIfChanged } from './_dotenv';
import { applyLocalOverridesForTarget, resolveSyncMode } from './_overrides';

type OutputFile = {
  target: EnvTarget;
  filePath: string;
  headerLines: string[];
};

const GROUP_ORDER: EnvVarGroup[] = [
  'App',
  'Auth',
  'JWT',
  'Workers',
  'Logs',
  'OAuth',
  'Email',
  'Upstash',
  'Cloudflare',
  'Turbo',
];

const renderTargetEnvFile = (
  target: EnvTarget,
  headerLines: string[],
  values: Record<string, string>,
  opts?: {
    includeVar?: (key: string) => boolean;
  },
) => {
  const vars = getEnvVarsForTarget(target).filter((v) =>
    opts?.includeVar ? opts.includeVar(v.key) : true,
  );
  const lines: string[] = [...headerLines, ''];

  for (const group of GROUP_ORDER) {
    const groupVars = vars.filter((v) => v.group === group);
    if (groupVars.length === 0) {
      continue;
    }

    lines.push(`# ${group}`);

    for (const v of groupVars) {
      if (v.description) {
        lines.push(`# ${v.description}`);
      }

      const value = values[v.key] ?? '';
      lines.push(`${v.key}=${formatDotenvValue(value)}`);
      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
};

const repoRoot = process.cwd();
const primarySourcePath = join(repoRoot, 'env', '.env');
const legacySourcePath = join(repoRoot, 'env', '.env.local');
const sourcePath = existsSync(primarySourcePath)
  ? primarySourcePath
  : existsSync(legacySourcePath)
    ? legacySourcePath
    : primarySourcePath;

if (!existsSync(sourcePath)) {
  console.error(
    `[env] Missing ${sourcePath}. Create it to sync local env files.\n` +
      '\n' +
      'Quick start:\n' +
      '  pnpm env:generate\n' +
      '  cp env/.env.example env/.env\n' +
      '  cp env/.vars.example env/.vars\n' +
      '  # edit env/.env\n' +
      '  # edit env/.vars\n' +
      '  pnpm env:bootstrap\n',
  );
  process.exit(1);
}

const sourceContent = readFileSync(sourcePath, 'utf-8');
const values = parseDotenv(sourceContent);
const syncMode = resolveSyncMode(process.env.DEEPCRAWL_ENV_SYNC_MODE);

const dotenvOutputs: OutputFile[] = [
  {
    target: 'dashboard',
    // Used by Drizzle/Better Auth CLI scripts and Next.js dev server.
    filePath: join(repoRoot, 'apps', 'app', '.env'),
    headerLines: [
      '# Auto-generated by `pnpm env:bootstrap`',
      `# Source: ${sourcePath}`,
      `# Mode: ${syncMode}`,
    ],
  },
  {
    target: 'worker-auth',
    filePath: join(repoRoot, 'apps', 'workers', 'auth', '.dev.vars'),
    headerLines: [
      '# Auto-generated by `pnpm env:bootstrap`',
      `# Source: ${sourcePath}`,
      `# Mode: ${syncMode}`,
      '# Note: Secrets only. Non-secrets live in wrangler.jsonc vars.',
      '#       Wrangler vars are synced from env/.vars.',
    ],
  },
  {
    target: 'worker-v0',
    filePath: join(repoRoot, 'apps', 'workers', 'v0', '.dev.vars'),
    headerLines: [
      '# Auto-generated by `pnpm env:bootstrap`',
      `# Source: ${sourcePath}`,
      `# Mode: ${syncMode}`,
      '# Note: Secrets only. Non-secrets live in wrangler.jsonc vars.',
      '#       Wrangler vars are synced from env/.vars.',
    ],
  },
];

let changed = 0;

for (const out of dotenvOutputs) {
  const resolvedValues = applyLocalOverridesForTarget(
    out.target,
    values,
    syncMode,
  );
  const content = (() => {
    if (out.target !== 'worker-auth' && out.target !== 'worker-v0') {
      return renderTargetEnvFile(out.target, out.headerLines, resolvedValues);
    }

    const secretKeys = new Set(
      getEnvVarsForTarget(out.target)
        .filter((v) => v.secret)
        .map((v) => v.key),
    );

    return renderTargetEnvFile(out.target, out.headerLines, resolvedValues, {
      includeVar: (key) => secretKeys.has(key),
    });
  })();
  const didWrite = writeFileIfChanged(out.filePath, content);
  if (didWrite) {
    changed += 1;
    console.log(`[env] wrote ${out.filePath}`);
  } else {
    console.log(`[env] up-to-date ${out.filePath}`);
  }
}

if (changed === 0) {
  console.log('[env] no changes');
}
