/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deepcrawlGetMarkdown } from "../../funcs/deepcrawlGetMarkdown.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMarkdownRequest$inboundSchema,
};

export const tool$deepcrawlGetMarkdown: ToolDefinition<typeof args> = {
  name: "deepcrawl-get-markdown",
  description: `Directly return page markdown content from the request URL.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deepcrawlGetMarkdown(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
