/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deepcrawlExtractLinks } from "../../funcs/deepcrawlExtractLinks.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ExtractLinksPostRequest$inboundSchema,
};

export const tool$deepcrawlExtractLinks: ToolDefinition<typeof args> = {
  name: "deepcrawl-extract-links",
  description: `Returning extracted links sitemap results for the request URL.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deepcrawlExtractLinks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
