packages:
  - "apps/*"
  - "packages/*"
  - "apps/workers/*"
  - "packages/db/db-d1"
  - "packages/db/db-auth"
  - "packages/sdks/js-ts"
catalog:
  "@cloudflare/workers-types": ^4.20250711.0
  "@dnd-kit/core": ^6.3.1
  "@dnd-kit/modifiers": ^9.0.0
  "@dnd-kit/sortable": ^10.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@eslint/eslintrc": ^3
  "@hookform/resolvers": ^5.1.1
  "@neondatabase/serverless": ^1.0.0
  "@orpc/client": ^1.8.7
  "@orpc/contract": ^1.8.7
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tabs": ^1.1.13
  "@radix-ui/react-toggle": ^1.1.9
  "@radix-ui/react-toggle-group": ^1.1.10
  "@radix-ui/react-tooltip": ^1.2.7
  "@tabler/icons-react": ^3.34.0
  "@tanstack/react-table": ^8.21.3
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  class-variance-authority: ^0.7.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  eslint: ^9.31.0
  eslint-config-next: ^16.0.0
  fumadocs-core: ^16.0.2
  fumadocs-ui: ^16.0.2
  lucide-react: ^0.544.0
  motion: ^12.23.16
  next-themes: ^0.4.6
  react: ^19.2.0
  react-day-picker: ^9.11.0
  react-dom: ^19.2.0
  react-hook-form: ^7.60.0
  recharts: 2.15.4
  sonner: ^2.0.7
  stoker: ^1.4.2
  tailwind-scrollbar: ^4.0.2
  typescript: ^5.9.3
  vaul: ^1.1.2
