packages:
  - "apps/*"
  - "packages/*"
  - "apps/workers/*"
  - "packages/db/db-d1"
  - "packages/db/db-auth"
  - "packages/sdks/js-ts"
catalog:
  "@cloudflare/workers-types": ^4.20260207.0
  "@biomejs/biome": ^2.3.14
  "@changesets/changelog-github": ^0.5.2
  "@changesets/cli": ^2.29.8
  "@dnd-kit/core": ^6.3.1
  "@dnd-kit/modifiers": ^9.0.0
  "@dnd-kit/sortable": ^10.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@eslint/eslintrc": ^3.3.3
  "@hookform/resolvers": ^5.2.2
  "@hono-rate-limiter/cloudflare": ^0.2.2
  "@hono/zod-openapi": ^1.2.1
  "@hono/zod-validator": ^0.7.6
  "@neondatabase/serverless": ^1.0.2
  "@orpc/client": ^1.13.4
  "@orpc/contract": ^1.13.4
  "@orpc/json-schema": ^1.13.4
  "@orpc/openapi": ^1.13.4
  "@orpc/openapi-client": ^1.13.4
  "@orpc/server": ^1.13.4
  "@orpc/zod": ^1.13.4
  "@radix-ui/react-avatar": ^1.1.11
  "@radix-ui/react-checkbox": ^1.3.3
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-label": ^2.1.8
  "@radix-ui/react-popover": ^1.1.15
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.8
  "@radix-ui/react-slot": ^1.2.4
  "@radix-ui/react-tabs": ^1.1.13
  "@radix-ui/react-toggle": ^1.1.10
  "@radix-ui/react-toggle-group": ^1.1.11
  "@radix-ui/react-tooltip": ^1.2.8
  "@tabler/icons-react": ^3.36.1
  "@tanstack/react-table": ^8.21.3
  "@types/node": ^22.19.10
  "@types/react": ^19.2.13
  "@types/react-dom": ^19.2.3
  better-auth: ^1.4.18
  class-variance-authority: ^0.7.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-next: ^16.1.6
  fumadocs-core: ^16.5.1
  fumadocs-ui: ^16.5.1
  hono: ^4.11.8
  hono-rate-limiter: ^0.5.3
  husky: ^9.1.7
  lint-staged: ^16.2.7
  lucide-react: ^0.563.0
  motion: ^12.33.0
  next: ^16.1.6
  next-themes: ^0.4.6
  react: ^19.2.4
  react-day-picker: ^9.13.1
  react-dom: ^19.2.4
  react-hook-form: ^7.71.1
  recharts: 3.7.0
  rimraf: ^6.1.2
  shadcn: ^3.8.4
  sonner: ^2.0.7
  stoker: ^2.0.1
  tailwind-scrollbar: ^4.0.2
  turbo: ^2.8.3
  typescript: ^5.9.3
  vaul: ^1.1.2
  wrangler: ^4.63.0
  zod: ^4.3.6
