import type {
  ExtractLinksPlaygroundResponse,
  ReadUrlPlaygroundResponse,
} from '@/hooks/playground/types';

export const readUrlResponseSample: ReadUrlPlaygroundResponse = {
  operation: 'readUrl',
  executionTime: 400,
  status: 200,
  data: {
    requestId: '81c5a50f-ae4a-457b-a165-38c712caff4e',
    success: true,
    cached: true,
    targetUrl: 'https://hono.dev',
    timestamp: '2025-10-19T12:16:35.810Z',
    title: 'Hono - Web framework built on Web Standards',
    description:
      'Web framework built on Web Standards for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Node.js, and others. Fast, but not only fast.',
    metadata: {
      title: 'Hono - Web framework built on Web Standards',
      description:
        'Web framework built on Web Standards for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Node.js, and others. Fast, but not only fast.',
      language: 'en-US',
      canonical: 'https://hono.dev/',
      favicon: 'https://hono.dev/favicon.ico',
      ogDescription:
        'Hono is a small, simple, and ultrafast web framework built on Web Standards. It works on Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Netlify, AWS Lambda, Lambda@Edge, and Node.js. Fast, but not only fast.',
      ogImage: 'https://hono.dev/images/hono-title.png',
      ogType: 'website',
      isIframeAllowed: true,
    },
    markdown:
      "## HonoWeb application framework\nFast, lightweight, built on Web Standards. Support for any JavaScript runtime.\n![An example of code for Hono. import { Hono } from 'hono' const app = new Hono() app.get('/', (c) => c.text('Hello Hono!')) export default app](https://hono.dev/images/code.webp)\n🚀\n## Ultrafast & Lightweight\nThe router RegExpRouter is really fast. The hono/tiny preset is under 14kB. Using only Web Standard APIs.\n🌍\n## Multi-runtime\nWorks on Cloudflare, Fastly, Deno, Bun, AWS, or Node.js. The same code runs on all platforms.\n🔋\n## Batteries Included\nHono has built-in middleware, custom middleware, third-party middleware, and helpers. Batteries included.\n😃\n## Delightful DX\nSuper clean APIs. First-class TypeScript support. Now, we've got \"Types\".",
    metrics: {
      readableDuration: '6.00ms',
      durationMs: 6,
      startTimeMs: 1760876195810,
      endTimeMs: 1760876195816,
    },
  },
} as const;

export const extractLinksResponseSample: ExtractLinksPlaygroundResponse = {
  operation: 'extractLinks',
  data: {
    success: true,
    targetUrl: 'https://hono.dev',
    timestamp: '2025-10-19T12:45:02.373Z',
    requestId: 'efe0e372-998e-47ba-8830-ce3ec16edb68',
    cached: false,
    metrics: {
      readableDuration: '3.52s',
      durationMs: 3521,
      startTimeMs: 1760877902372,
      endTimeMs: 1760877905893,
    },
    tree: {
      url: 'https://hono.dev',
      rootUrl: 'https://hono.dev',
      name: 'hono.dev',
      totalUrls: 117,
      lastUpdated: '2025-10-19T12:45:05.885Z',
      lastVisited: '2025-10-19T12:45:04.648Z',
      metadata: {
        title: 'Hono - Web framework built on Web Standards',
        description:
          'Web framework built on Web Standards for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Node.js, and others. Fast, but not only fast.',
        language: 'en-US',
        canonical: 'https://hono.dev/',
        favicon: 'https://hono.dev/favicon.ico',
        ogDescription:
          'Hono is a small, simple, and ultrafast web framework built on Web Standards. It works on Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Netlify, AWS Lambda, Lambda@Edge, and Node.js. Fast, but not only fast.',
        ogImage: 'https://hono.dev/images/hono-title.png',
        ogType: 'website',
        isIframeAllowed: true,
      },
      extractedLinks: {
        internal: ['https://hono.dev/docs', 'https://hono.dev/examples'],
      },
      children: [
        {
          url: 'https://hono.dev/docs',
          name: 'docs',
          lastUpdated: '2025-10-19T12:45:05.885Z',
          lastVisited: '2025-10-19T12:45:05.316Z',
          metadata: {
            title: 'Hono - Web framework built on Web Standards',
            description:
              'Web framework built on Web Standards for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Node.js, and others. Fast, but not only fast.',
            language: 'en-US',
            canonical: 'https://hono.dev/docs',
            favicon: 'https://hono.dev/favicon.ico',
            ogImage: 'https://hono.dev/images/hono-title.png',
            ogType: 'website',
            isIframeAllowed: true,
          },
          extractedLinks: {
            internal: [
              'https://hono.dev/docs',
              'https://hono.dev/examples',
              'https://hono.dev/docs/concepts/motivation',
              'https://hono.dev/docs/concepts/routers',
              'https://hono.dev/docs/concepts/benchmarks',
              'https://hono.dev/docs/concepts/web-standard',
              'https://hono.dev/docs/concepts/middleware',
              'https://hono.dev/docs/concepts/developer-experience',
              'https://hono.dev/docs/concepts/stacks',
              'https://hono.dev/docs/getting-started/basic',
              'https://hono.dev/docs/getting-started/cloudflare-workers',
              'https://hono.dev/docs/getting-started/cloudflare-pages',
              'https://hono.dev/docs/getting-started/deno',
              'https://hono.dev/docs/getting-started/bun',
              'https://hono.dev/docs/getting-started/fastly',
              'https://hono.dev/docs/getting-started/vercel',
              'https://hono.dev/docs/getting-started/nextjs',
              'https://hono.dev/docs/getting-started/netlify',
              'https://hono.dev/docs/getting-started/aws-lambda',
              'https://hono.dev/docs/getting-started/lambda-edge',
              'https://hono.dev/docs/getting-started/azure-functions',
              'https://hono.dev/docs/getting-started/google-cloud-run',
              'https://hono.dev/docs/getting-started/supabase-functions',
              'https://hono.dev/docs/getting-started/ali-function-compute',
              'https://hono.dev/docs/getting-started/service-worker',
              'https://hono.dev/docs/getting-started/nodejs',
              'https://hono.dev/docs/api/hono',
              'https://hono.dev/docs/api/routing',
              'https://hono.dev/docs/api/context',
              'https://hono.dev/docs/api/request',
              'https://hono.dev/docs/api/exception',
              'https://hono.dev/docs/api/presets',
              'https://hono.dev/docs/guides/create-hono',
              'https://hono.dev/docs/guides/middleware',
              'https://hono.dev/docs/guides/helpers',
              'https://hono.dev/docs/guides/jsx',
              'https://hono.dev/docs/guides/jsx-dom',
              'https://hono.dev/docs/guides/testing',
              'https://hono.dev/docs/guides/validation',
              'https://hono.dev/docs/guides/rpc',
              'https://hono.dev/docs/guides/best-practices',
              'https://hono.dev/docs/guides/others',
              'https://hono.dev/docs/guides/faq',
              'https://hono.dev/docs/helpers/accepts',
              'https://hono.dev/docs/helpers/adapter',
              'https://hono.dev/docs/helpers/conninfo',
              'https://hono.dev/docs/helpers/cookie',
              'https://hono.dev/docs/helpers/css',
              'https://hono.dev/docs/helpers/dev',
              'https://hono.dev/docs/helpers/factory',
              'https://hono.dev/docs/helpers/html',
              'https://hono.dev/docs/helpers/jwt',
              'https://hono.dev/docs/helpers/proxy',
              'https://hono.dev/docs/helpers/route',
              'https://hono.dev/docs/helpers/ssg',
              'https://hono.dev/docs/helpers/streaming',
              'https://hono.dev/docs/helpers/testing',
              'https://hono.dev/docs/helpers/websocket',
              'https://hono.dev/docs/middleware/builtin/basic-auth',
              'https://hono.dev/docs/middleware/builtin/bearer-auth',
              'https://hono.dev/docs/middleware/builtin/body-limit',
              'https://hono.dev/docs/middleware/builtin/cache',
              'https://hono.dev/docs/middleware/builtin/combine',
              'https://hono.dev/docs/middleware/builtin/compress',
              'https://hono.dev/docs/middleware/builtin/context-storage',
              'https://hono.dev/docs/middleware/builtin/cors',
              'https://hono.dev/docs/middleware/builtin/csrf',
              'https://hono.dev/docs/middleware/builtin/etag',
              'https://hono.dev/docs/middleware/builtin/ip-restriction',
              'https://hono.dev/docs/middleware/builtin/jsx-renderer',
              'https://hono.dev/docs/middleware/builtin/jwk',
              'https://hono.dev/docs/middleware/builtin/jwt',
              'https://hono.dev/docs/middleware/builtin/logger',
              'https://hono.dev/docs/middleware/builtin/language',
              'https://hono.dev/docs/middleware/builtin/method-override',
              'https://hono.dev/docs/middleware/builtin/pretty-json',
              'https://hono.dev/docs/middleware/builtin/request-id',
              'https://hono.dev/docs/middleware/builtin/secure-headers',
              'https://hono.dev/docs/middleware/builtin/timeout',
              'https://hono.dev/docs/middleware/builtin/timing',
              'https://hono.dev/docs/middleware/builtin/trailing-slash',
              'https://hono.dev/docs/middleware/third-party',
              'https://hono.dev/llms.txt',
              'https://hono.dev/llms-full.txt',
              'https://hono.dev/llms-small.txt',
            ],
          },
          children: [
            {
              url: 'https://hono.dev/docs/concepts',
              name: 'concepts',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/concepts/motivation',
                  name: 'motivation',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/routers',
                  name: 'routers',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/benchmarks',
                  name: 'benchmarks',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/web-standard',
                  name: 'web-standard',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/middleware',
                  name: 'middleware',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/developer-experience',
                  name: 'developer-experience',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/concepts/stacks',
                  name: 'stacks',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
            {
              url: 'https://hono.dev/docs/getting-started',
              name: 'getting-started',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/getting-started/basic',
                  name: 'basic',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/cloudflare-workers',
                  name: 'cloudflare-workers',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/cloudflare-pages',
                  name: 'cloudflare-pages',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/deno',
                  name: 'deno',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/bun',
                  name: 'bun',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/fastly',
                  name: 'fastly',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/vercel',
                  name: 'vercel',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/nextjs',
                  name: 'nextjs',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/netlify',
                  name: 'netlify',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/aws-lambda',
                  name: 'aws-lambda',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/lambda-edge',
                  name: 'lambda-edge',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/azure-functions',
                  name: 'azure-functions',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/google-cloud-run',
                  name: 'google-cloud-run',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/supabase-functions',
                  name: 'supabase-functions',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/ali-function-compute',
                  name: 'ali-function-compute',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/service-worker',
                  name: 'service-worker',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/getting-started/nodejs',
                  name: 'nodejs',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
            {
              url: 'https://hono.dev/docs/api',
              name: 'api',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/api/hono',
                  name: 'hono',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/api/routing',
                  name: 'routing',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/api/context',
                  name: 'context',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/api/request',
                  name: 'request',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/api/exception',
                  name: 'exception',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/api/presets',
                  name: 'presets',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
            {
              url: 'https://hono.dev/docs/guides',
              name: 'guides',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/guides/create-hono',
                  name: 'create-hono',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/middleware',
                  name: 'middleware',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/helpers',
                  name: 'helpers',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/jsx',
                  name: 'jsx',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/jsx-dom',
                  name: 'jsx-dom',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/testing',
                  name: 'testing',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/validation',
                  name: 'validation',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/rpc',
                  name: 'rpc',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/best-practices',
                  name: 'best-practices',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/others',
                  name: 'others',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/guides/faq',
                  name: 'faq',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
            {
              url: 'https://hono.dev/docs/helpers',
              name: 'helpers',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/helpers/accepts',
                  name: 'accepts',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/adapter',
                  name: 'adapter',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/conninfo',
                  name: 'conninfo',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/cookie',
                  name: 'cookie',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/css',
                  name: 'css',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/dev',
                  name: 'dev',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/factory',
                  name: 'factory',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/html',
                  name: 'html',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/jwt',
                  name: 'jwt',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/proxy',
                  name: 'proxy',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/route',
                  name: 'route',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/ssg',
                  name: 'ssg',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/streaming',
                  name: 'streaming',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/testing',
                  name: 'testing',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
                {
                  url: 'https://hono.dev/docs/helpers/websocket',
                  name: 'websocket',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
            {
              url: 'https://hono.dev/docs/middleware',
              name: 'middleware',
              lastUpdated: '2025-10-19T12:45:05.885Z',
              children: [
                {
                  url: 'https://hono.dev/docs/middleware/builtin',
                  name: 'builtin',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                  children: [
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/basic-auth',
                      name: 'basic-auth',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/bearer-auth',
                      name: 'bearer-auth',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/body-limit',
                      name: 'body-limit',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/cache',
                      name: 'cache',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/combine',
                      name: 'combine',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/compress',
                      name: 'compress',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/context-storage',
                      name: 'context-storage',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/cors',
                      name: 'cors',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/csrf',
                      name: 'csrf',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/etag',
                      name: 'etag',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/ip-restriction',
                      name: 'ip-restriction',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/jsx-renderer',
                      name: 'jsx-renderer',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/jwk',
                      name: 'jwk',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/jwt',
                      name: 'jwt',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/logger',
                      name: 'logger',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/language',
                      name: 'language',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/method-override',
                      name: 'method-override',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/pretty-json',
                      name: 'pretty-json',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/request-id',
                      name: 'request-id',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/secure-headers',
                      name: 'secure-headers',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/timeout',
                      name: 'timeout',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/timing',
                      name: 'timing',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                    {
                      url: 'https://hono.dev/docs/middleware/builtin/trailing-slash',
                      name: 'trailing-slash',
                      lastUpdated: '2025-10-19T12:45:05.885Z',
                    },
                  ],
                },
                {
                  url: 'https://hono.dev/docs/middleware/third-party',
                  name: 'third-party',
                  lastUpdated: '2025-10-19T12:45:05.885Z',
                },
              ],
            },
          ],
        },
        {
          url: 'https://hono.dev/examples',
          name: 'examples',
          lastUpdated: '2025-10-19T12:45:05.885Z',
          lastVisited: '2025-10-19T12:45:05.882Z',
          metadata: {
            title: 'Examples - Hono',
            description:
              'Web framework built on Web Standards for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Node.js, and others. Fast, but not only fast.',
            language: 'en-US',
            canonical: 'https://hono.dev/examples',
            favicon: 'https://hono.dev/favicon.ico',
            ogImage: 'https://hono.dev/images/hono-title.png',
            ogType: 'website',
            isIframeAllowed: true,
          },
          extractedLinks: {
            internal: [
              'https://hono.dev/docs',
              'https://hono.dev/examples',
              'https://hono.dev/examples/web-api',
              'https://hono.dev/examples/proxy',
              'https://hono.dev/examples/file-upload',
              'https://hono.dev/examples/behind-reverse-proxy',
              'https://hono.dev/examples/validator-error-handling',
              'https://hono.dev/examples/grouping-routes-rpc',
              'https://hono.dev/examples/cbor',
              'https://hono.dev/examples/zod-openapi',
              'https://hono.dev/examples/hono-openapi',
              'https://hono.dev/examples/swagger-ui',
              'https://hono.dev/examples/scalar',
              'https://hono.dev/examples/hono-docs',
              'https://hono.dev/examples/cloudflare-durable-objects',
              'https://hono.dev/examples/cloudflare-queue',
              'https://hono.dev/examples/cloudflare-vitest',
              'https://hono.dev/examples/with-remix',
              'https://hono.dev/examples/htmx',
              'https://hono.dev/examples/stripe-webhook',
              'https://hono.dev/examples/prisma',
              'https://hono.dev/examples/better-auth',
              'https://hono.dev/examples/better-auth-on-cloudflare',
              'https://hono.dev/examples/pylon',
              'https://hono.dev/examples/stytch-auth',
              'https://hono.dev/examples/hono-authjs',
            ],
          },
          children: [
            {
              url: 'https://hono.dev/examples/web-api',
              name: 'web-api',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/proxy',
              name: 'proxy',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/file-upload',
              name: 'file-upload',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/behind-reverse-proxy',
              name: 'behind-reverse-proxy',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/validator-error-handling',
              name: 'validator-error-handling',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/grouping-routes-rpc',
              name: 'grouping-routes-rpc',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/cbor',
              name: 'cbor',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/zod-openapi',
              name: 'zod-openapi',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/hono-openapi',
              name: 'hono-openapi',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/swagger-ui',
              name: 'swagger-ui',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/scalar',
              name: 'scalar',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/hono-docs',
              name: 'hono-docs',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/cloudflare-durable-objects',
              name: 'cloudflare-durable-objects',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/cloudflare-queue',
              name: 'cloudflare-queue',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/cloudflare-vitest',
              name: 'cloudflare-vitest',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/with-remix',
              name: 'with-remix',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/htmx',
              name: 'htmx',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/stripe-webhook',
              name: 'stripe-webhook',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/prisma',
              name: 'prisma',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/better-auth',
              name: 'better-auth',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/better-auth-on-cloudflare',
              name: 'better-auth-on-cloudflare',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/pylon',
              name: 'pylon',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/stytch-auth',
              name: 'stytch-auth',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
            {
              url: 'https://hono.dev/examples/hono-authjs',
              name: 'hono-authjs',
              lastUpdated: '2025-10-19T12:45:05.885Z',
            },
          ],
        },
        {
          url: 'https://hono.dev/llms.txt',
          name: 'llms.txt',
          lastUpdated: '2025-10-19T12:45:05.885Z',
        },
        {
          url: 'https://hono.dev/llms-full.txt',
          name: 'llms-full.txt',
          lastUpdated: '2025-10-19T12:45:05.885Z',
        },
        {
          url: 'https://hono.dev/llms-small.txt',
          name: 'llms-small.txt',
          lastUpdated: '2025-10-19T12:45:05.885Z',
        },
      ],
    },
  },
  status: 200,
  executionTime: 7676.200000000186,
  targetUrl: 'https://hono.dev',
  timestamp: '2025-10-19T12:45:06.082Z',
  retryable: false,
};
